Added Pull_request_template.md
TheRenegadeCoder/sample-programs-website pull request #328
Opened 2020-10-02 18:51 UTC by UdokaVrede

This P.R fixes issue number #315

2020-10-04 18:55 UTC, jrg94 requested changes
This is a really cool idea! Since this is a repo mostly for articles, I don't know that some of this stuff applies. What do you think?

2020-10-06 10:25 UTC, UdokaVrede commented
oh right I would fix this now

2020-10-07 02:48 UTC, jrg94 commented
I added some new stuff to the main README. Perhaps this could help: https://github.com/TheRenegadeCoder/sample-programs-website/blob/master/README.md

2020-10-07 06:06 UTC, UdokaVrede commented
Alright

2020-10-07 06:19 UTC, UdokaVrede commented
Can you give some more details pls

2020-10-07 23:53 UTC, jrg94 requested changes
Looking better! I think we can more or less just use this check list. Everything else can probably be removed. 👍

2020-10-07 23:53 UTC, jrg94 commented on pull_request_template.md
> +```
```suggestion

```

2020-10-07 23:53 UTC, jrg94 commented on pull_request_template.md
> +For a guide, on making your pull request, see [Pull_Request](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)
```suggestion

```

2020-10-07 23:53 UTC, jrg94 commented on pull_request_template.md
> +[ ] Language Documentation content
```suggestion
- [ ] Language Documentation
```

2020-10-07 23:53 UTC, jrg94 commented on pull_request_template.md
> +[ ] Project Documentation content
```suggestion
- [ ] Project Documentation
```

2020-10-07 23:53 UTC, jrg94 commented on pull_request_template.md
> +[ ] Sample program
```suggestion
- [ ] Sample Program Documentation
```

2020-10-08 06:48 UTC, UdokaVrede reviewed
This looks good, thanks

2020-10-08 18:22 UTC, merged