added longest palindrome substring using the best method in C++
TheRenegadeCoder/sample-programs-website pull request #335
Opened 2020-10-05 14:52 UTC by hemabhravee

2020-10-05 14:53 UTC, hemabhravee commented
If you find the article satisfactory, please add the hacktoberfest label to this PR before merging

2020-10-05 18:28 UTC, jrg94 requested changes
Looks great! Have you submitted this over in the main repo yet? Also, make sure to add yourself to the authors file.

2020-10-05 20:28 UTC, hemabhravee commented
Do I have to submit this in some other repo as well? If so, please tell me where.

2020-10-05 20:32 UTC, jrg94 commented
It would go here: https://github.com/TheRenegadeCoder/sample-programs

That way, it can get tested and you can document the results here.

2020-10-05 20:40 UTC, hemabhravee commented
Got it! Thanks a lot.

2020-10-07 03:21 UTC, jrg94 requested changes
This is awesome, but I don't currently see a working solution to this here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/c/c-plus-plus

I assume you have a pull request that this is referencing, but I don't believe we have testing implemented yet. It's not a big deal, but we'll have to work through the code-side first.

2020-10-07 03:21 UTC, jrg94 commented on projects/longest-palindrome-substring/_posts/2020-10-3-c-plus-plus.md
> +title: Longest Palindromic Substring in Every Language
```suggestion
title: Longest Palindromic Substring in C++
```

2020-10-07 03:21 UTC, jrg94 commented on projects/longest-palindrome-substring/_posts/2020-10-3-c-plus-plus.md
> +  - Hemabh Ravee
```suggestion
  - hemabhravee
```

2021-08-13 02:20 UTC, jrg94 commented on projects/longest-palindrome-substring/_posts/2020-10-3-c-plus-plus.md
> +  - Sayantan Paul
```suggestion

```

2021-08-13 02:22 UTC, closed without merging